version: '3.7'

services:

  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '33060:3306'
    environment:
      MYSQL_DATABASE: institute
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - "./resources/sql:/docker-entrypoint-initdb.d:ro"
    networks:
      - default

networks:
  default:
