version: '3.7'

services:

  php:
    build:
      context: .
      dockerfile: resources/dc/php/Dockerfile
    entrypoint: [ ]
    command: [ ]
    tty: true
    stdin_open: true
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: institute
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - "./resources/sql:/docker-entrypoint-initdb.d:ro"
    networks:
      - default

networks:
  default:
