services:

  mysql:
    image: mysql:8
    ports:
      - '33060:3306'
    environment:
      MYSQL_DATABASE: institute
      MYSQL_USER: groot
      MYSQL_PASSWORD: groot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - "./resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    networks:
      - default

networks:
  default:
