-- MySQL Script generated by MySQL Workbench
-- Sat 10 Apr 2021 08:59:35 CEST
-- Model: Samples    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema samples
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `samples` ;

-- -----------------------------------------------------
-- Schema samples
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `samples` DEFAULT CHARACTER SET utf8 ;
USE `samples` ;

-- -----------------------------------------------------
-- Table `samples`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`User` ;

CREATE TABLE IF NOT EXISTS `samples`.`User` (
  `idUser` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(200) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`UserProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`UserProfile` ;

CREATE TABLE IF NOT EXISTS `samples`.`UserProfile` (
  `idUserProfile` INT NOT NULL,
  `driverLicense` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idUserProfile`),
  UNIQUE INDEX `documentNumber_UNIQUE` (`driverLicense` ASC),
  INDEX `fk_UserProfile_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_UserProfile_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `samples`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`country` ;

CREATE TABLE IF NOT EXISTS `samples`.`country` (
  `idCountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`city` ;

CREATE TABLE IF NOT EXISTS `samples`.`city` (
  `idCity` INT NOT NULL,
  `Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_City_Country1_idx` (`Country_idCountry` ASC),
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `samples`.`country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`course` ;

CREATE TABLE IF NOT EXISTS `samples`.`course` (
  `idCourse` INT NOT NULL,
  PRIMARY KEY (`idCourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`student` ;

CREATE TABLE IF NOT EXISTS `samples`.`student` (
  `idStudent` INT NOT NULL,
  `Course_idCourse` INT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_Student_Course1_idx` (`Course_idCourse` ASC),
  CONSTRAINT `fk_Student_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `samples`.`course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`car` ;

CREATE TABLE IF NOT EXISTS `samples`.`car` (
  `idcar` INT NOT NULL,
  `plate` VARCHAR(45) NULL,
  PRIMARY KEY (`idcar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`driver` ;

CREATE TABLE IF NOT EXISTS `samples`.`driver` (
  `iddriver` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`iddriver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`driver_rents_car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`driver_rents_car` ;

CREATE TABLE IF NOT EXISTS `samples`.`driver_rents_car` (
  `car_idcar` INT NOT NULL,
  `client_iddriver` INT NOT NULL,
  `rentedAt` DATETIME NULL,
  PRIMARY KEY (`car_idcar`, `client_iddriver`),
  INDEX `fk_car_has_client_client1_idx` (`client_iddriver` ASC),
  INDEX `fk_car_has_client_car1_idx` (`car_idcar` ASC),
  UNIQUE INDEX `rentedAt_UNIQUE` (`rentedAt` ASC),
  CONSTRAINT `fk_car_has_client_car1`
    FOREIGN KEY (`car_idcar`)
    REFERENCES `samples`.`car` (`idcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_has_client_client1`
    FOREIGN KEY (`client_iddriver`)
    REFERENCES `samples`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`client` ;

CREATE TABLE IF NOT EXISTS `samples`.`client` (
  `idclient` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samples`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples`.`seat` ;

CREATE TABLE IF NOT EXISTS `samples`.`seat` (
  `idseat` INT NOT NULL,
  `row` VARCHAR(45) NULL,
  `column` VARCHAR(45) NULL,
  `client_idclient` INT NULL,
  PRIMARY KEY (`idseat`),
  INDEX `fk_seat_client1_idx` (`client_idclient` ASC),
  CONSTRAINT `fk_seat_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `samples`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
