@startuml

title DB visualizer
skinparam ArrowFontColor Black
skinparam ArrowThickness 2
skinparam UseCaseBackgroundColor #FFFECC
skinparam UseCaseBorderColor #333333
skinparam UseCaseBorderThickness 2
skinparam UseCaseFontColor Black

(setup)
(qa)
(dc:up)
(dc:stop)
(dc:down)
(dc:ip)
(dc:shell)
(qa:remote)
(phpstan:analyze)
(composer:validate)
(composer:normalize)
(composer:install)
(docs:images)
(phpunit:run)
(wait-for-database)
(help)


(setup) -[#5D9CEC]-> (composer:install) : depend:1
(setup) -[#5D9CEC]-> (dc:up) : depend:2
(setup) -[#5D9CEC]-> (dc:ip) : depend:3
(qa) -[#5D9CEC]-> (composer:validate) : depend:1
(qa) -[#5D9CEC]-> (composer:normalize) : depend:2
(qa) -[#5D9CEC]-> (phpstan:analyze) : depend:3
(qa) -[#5D9CEC]-> (phpunit:run) : depend:4
(phpunit:run) -[#5D9CEC]-> (wait-for-database) : depend:1

@enduml
